version: '2.1'
services:
  psripper:
        image: tom42/ps_youtube_dl
        container_name: psripper
        volumes:
            - /WHERE YOU PUT ripper.ini:/PSripper/config
            - /WHERE TO SAVE VIDEOS:/media
        restart: always
        
networks:
  default:
    external:
      name: nginx-proxy        
